#ifndef ERRNO_H
#define ERRNO_H

typedef enum {
  SUCCESS = 0,
  ERR_FILE_NOT_FOUND,
  ERR_FILE_READ,
  ERR_FILE_TOO_LARGE,
  ERR_INVALID_FORMAT,
  ERR_UNSUPPORTED_OPCODE,
  ERR_INVALID_OPERAND,
  ERR_STACK_OVERFLOW,
  ERR_STACK_UNDERFLOW,
  ERR_OUT_OF_MEMORY,
  ERR_EXECUTION_HALTED,
  ERR_NULL_POINTER,
  ERR_DIVIDE_BY_ZERO,
  ERR_UNKNOWN
} ErrorCode;

#endif // ERRNO_H
